# prompts.py
# Location: ai-contact-assistant-trece-art-studio/prompts.py

"""
Prompt template and structured output schema for the analyze_query node.
The schema is the contract: analyze_query will always return an instance
of QueryAnalysis, never raw text to parse by hand.
"""

from typing import Literal

from langchain_core.prompts import ChatPromptTemplate
from pydantic import BaseModel, Field


class QueryAnalysis(BaseModel):
    """
    Structured output for the client message analysis step.
    Field descriptions are not just documentation for humans -
    they are sent to the LLM as part of the function-calling schema,
    so they directly influence how the model fills each field.
    """

    service_type: Literal["illustration", "web_development", "ai_automation", "other"] = Field(
        description=(
            "The type of service the client is asking about. "
            "'illustration' for hand-drawn illustration work (book covers, "
            "reading clubs, social-impact projects, or an accent illustration "
            "for a web project). 'web_development' for fullstack web "
            "development work. 'ai_automation' for AI/agent/automation "
            "projects. 'other' if it doesn't match any of these."
        )
    )
    definition_level: Literal["low", "medium", "high"] = Field(
        description=(
            "How defined the request is. 'low' if vague (e.g. 'I want "
            "something cool'), 'high' if it includes clear specs, "
            "references, or deadlines."
        )
    )
    urgency: Literal["low", "medium", "high"] = Field(
        description="How urgent the client's request sounds, based on their wording."
    )
    is_valid_project: bool = Field(
        description=(
            "True if this is a legitimate project request within Trece Art "
            "Studio's scope. False for spam, irrelevant messages, or requests "
            "clearly outside scope."
        )
    )


# Analysis prompt: the system message sets the role and business rules,
# which stay fixed across every incoming message. The human message is the
# variable part, with the {client_message} placeholder that agent.py fills
# in at runtime with the actual client message.
ANALYSIS_PROMPT = ChatPromptTemplate.from_messages(
    [
        (
            "system",
            "You are an assistant that triages incoming client messages for "
            "Trece Art Studio, an independent studio offering three services: "
            "hand-drawn illustration for projects (book covers, reading clubs, "
            "social-impact projects, or as an accent piece for a web project), "
            "fullstack web development, and AI/automation projects. Analyze "
            "the message and extract the requested fields. Be conservative: "
            "if something is ambiguous, prefer the option that best matches "
            "what a real client of this kind of studio would say. This step "
            "only analyzes - you are not writing a reply yet. Note for later "
            "steps: any client-facing reply generated further in the flow "
            "must be written in the same language the client used in their "
            "message, whatever that is.",
        ),
        ("human", "{client_message}"),
    ]
)

# Prompt for propose_node — drafts only the body of the acceptance email
# Signature/contact info is appended separately in agent.py (see EMAIL_SIGNATURE below),
# never generated by the LLM, to avoid hallucinated contact details
PROPOSE_PROMPT = ChatPromptTemplate.from_messages([
    ("system",
     "You are the contact assistant for Trece Art Studio, a design, illustration, "
     "and web development studio. Write the BODY of an email accepting a client's "
     "inquiry. Reply in the same language the client used. "
     "Do not mention prices or exact delivery timelines — those are discussed later. "
     "Do not include a signature or closing — only the message body. "
     "If the definition level is 'low', politely ask for the missing details "
     "needed to scope the project."),
    ("human",
     "Client message: {client_message}\n"
     "Service type: {service_type}\n"
     "Definition level: {definition_level}\n"
     "Urgency: {urgency}")
])

# Prompt for reject_node — drafts a polite decline for out-of-scope inquiries
REJECT_PROMPT = ChatPromptTemplate.from_messages([
    ("system",
     "You are the contact assistant for Trece Art Studio. Write the BODY of a "
     "polite email declining a client's inquiry because it falls outside the "
     "studio's current services (illustration, web development, AI automation). "
     "Reply in the same language the client used. Be warm and brief. "
     "Do not include a signature or closing — only the message body."),
    ("human", "Client message: {client_message}")
])

# Fixed closing signature — hardcoded, never generated by the LLM
EMAIL_SIGNATURE = (
    "\n\n— Camila Chirino Castell\n"
    "Trece Art Studio — Project illustration\n"
    "What world do you want to illustrate?\n"
    "info.treceartstudio@gmail.com"
)